# Project: Fern
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"L:/Programs/DevCPPPortable/App/devcpp/lib" -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32  
INCS =  -I"L:/Programs/DevCPPPortable/App/devcpp/include" 
CXXINCS =  -I"L:/Programs/DevCPPPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"L:/Programs/DevCPPPortable/App/devcpp/include/c++/3.4.2/backward"  -I"L:/Programs/DevCPPPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"L:/Programs/DevCPPPortable/App/devcpp/include/c++/3.4.2"  -I"L:/Programs/DevCPPPortable/App/devcpp/include" 
BIN  = Fern.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Fern.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Fern.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
